[package]
name = "wrapped_string_type_macro"
version = "0.1.1"
authors = ["mmmpa <mmmpa.mmmpa@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"

[dev-dependencies]
serde = { version = "^1.0.105", features = ["derive", "rc"] }
serde_json = "1.0"
